// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CreatenewSiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createnewSite() {
    // Test name: Create new Site
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:8080/");
    // 2 | setWindowSize | 1707x1017 | 
    driver.manage().window().setSize(new Dimension(1707, 1017));
    // 3 | click | css=.lexicon-icon-grid > use | 
    driver.findElement(By.cssSelector(".lexicon-icon-grid > use")).click();
    // 4 | click | css=#\_com_liferay_product_navigation_applications_menu_web_internal_portlet_ProductNavigationApplicationsMenuPortlet_tab_2 > .nav-link | 
    driver.findElement(By.cssSelector("#\\_com_liferay_product_navigation_applications_menu_web_internal_portlet_ProductNavigationApplicationsMenuPortlet_tab_2 > .nav-link")).click();
    // 5 | click | css=.tab-pane:nth-child(3) .col-md:nth-child(3) .c-mt-2:nth-child(1) span | 
    driver.findElement(By.cssSelector(".tab-pane:nth-child(3) .col-md:nth-child(3) .c-mt-2:nth-child(1) span")).click();
    // 6 | click | linkText=New | 
    driver.findElement(By.linkText("New")).click();
    // 7 | click | css=.lexicon-icon-site-template > use | 
    driver.findElement(By.cssSelector(".lexicon-icon-site-template > use")).click();
    // 8 | selectFrame | index=0 | 
    driver.switchTo().frame(0);
    // 9 | click | id=_com_liferay_site_admin_web_portlet_SiteAdminPortlet_name | 
    driver.findElement(By.id("_com_liferay_site_admin_web_portlet_SiteAdminPortlet_name")).click();
    // 10 | type | id=_com_liferay_site_admin_web_portlet_SiteAdminPortlet_name | Inetum Robotic
    driver.findElement(By.id("_com_liferay_site_admin_web_portlet_SiteAdminPortlet_name")).sendKeys("Inetum Robotic");
    // 11 | click | css=#\_com_liferay_site_admin_web_portlet_SiteAdminPortlet_zzch > .lfr-btn-label | 
    driver.findElement(By.cssSelector("#\\_com_liferay_site_admin_web_portlet_SiteAdminPortlet_zzch > .lfr-btn-label")).click();
    // 12 | selectFrame | relative=parent | 
    driver.switchTo().defaultContent();
    // 13 | click | css=.lexicon-icon-product-menu-closed > use | 
    driver.findElement(By.cssSelector(".lexicon-icon-product-menu-closed > use")).click();
    // 14 | click | id=_com_liferay_product_navigation_product_menu_web_portlet_ProductMenuPortlet_pagesTreeSidenavToggleId | 
    driver.findElement(By.id("_com_liferay_product_navigation_product_menu_web_portlet_ProductMenuPortlet_pagesTreeSidenavToggleId")).click();
    // 15 | click | css=.lexicon-icon-plus > use | 
    driver.findElement(By.cssSelector(".lexicon-icon-plus > use")).click();
    // 16 | click | css=#clay-dropdown-menu-11 .dropdown-item | 
    driver.findElement(By.cssSelector("#clay-dropdown-menu-11 .dropdown-item")).click();
    // 17 | click | css=.card-item-first | 
    driver.findElement(By.cssSelector(".card-item-first")).click();
    // 18 | selectFrame | index=0 | 
    driver.switchTo().frame(0);
    // 19 | click | id=_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_name | 
    driver.findElement(By.id("_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_name")).click();
    // 20 | type | id=_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_name | Home
    driver.findElement(By.id("_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_name")).sendKeys("Home");
    // 21 | click | css=#\_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_addButton > .lfr-btn-label | 
    driver.findElement(By.cssSelector("#\\_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_addButton > .lfr-btn-label")).click();
    // 22 | selectFrame | relative=parent | 
    driver.switchTo().defaultContent();
    // 23 | dragAndDropToObject | css=.disabled > .align-items-center | css=.page-editor__no-fragments-state
    {
      WebElement dragged = driver.findElement(By.cssSelector(".disabled > .align-items-center"));
      WebElement dropped = driver.findElement(By.cssSelector(".page-editor__no-fragments-state"));
      Actions builder = new Actions(driver);
      builder.dragAndDrop(dragged, dropped).perform();
    }
    // 24 | dragAndDropToObject | css=.disabled > .align-items-center | id=lfr-479680a3-7aa9-40c9-8937-9f0e9d2da28d
    {
      WebElement dragged = driver.findElement(By.cssSelector(".disabled > .align-items-center"));
      WebElement dropped = driver.findElement(By.id("lfr-479680a3-7aa9-40c9-8937-9f0e9d2da28d"));
      Actions builder = new Actions(driver);
      builder.dragAndDrop(dragged, dropped).perform();
    }
    // 25 | click | css=.component-html | 
    driver.findElement(By.cssSelector(".component-html")).click();
    // 26 | click | css=.component-html | 
    driver.findElement(By.cssSelector(".component-html")).click();
    // 27 | doubleClick | css=.component-html | 
    {
      WebElement element = driver.findElement(By.cssSelector(".component-html"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 28 | click | css=div:nth-child(2) > .CodeMirror-line > span | 
    driver.findElement(By.cssSelector("div:nth-child(2) > .CodeMirror-line > span")).click();
    // 29 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 30 | click | css=.CodeMirror-code | 
    driver.findElement(By.cssSelector(".CodeMirror-code")).click();
    // 31 | mouseOver | css=.btn-group-spaced > .btn-primary | 
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-group-spaced > .btn-primary"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 32 | type | css=textarea | Welcome to home page
    driver.findElement(By.cssSelector("textarea")).sendKeys("Welcome to home page");
    // 33 | click | css=.btn-group-spaced > .btn-primary | 
    driver.findElement(By.cssSelector(".btn-group-spaced > .btn-primary")).click();
    // 34 | click | css=.btn-primary | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
    // 35 | click | css=.lexicon-icon-product-menu-closed | 
    driver.findElement(By.cssSelector(".lexicon-icon-product-menu-closed")).click();
    // 36 | mouseOver | css=.lexicon-icon-product-menu-closed | 
    {
      WebElement element = driver.findElement(By.cssSelector(".lexicon-icon-product-menu-closed"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 37 | mouseOut | css=.lexicon-icon-product-menu-closed | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 38 | click | linkText=Home | 
    driver.findElement(By.linkText("Home")).click();
    // 39 | mouseOver | linkText=Inetum Robotic | 
    {
      WebElement element = driver.findElement(By.linkText("Inetum Robotic"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
